/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  important: true,
  theme: {
    extend: {
      screens: {
        xsm: "500px",
        smd: "700px",
        lmd: "950px",
        vlg: "1024px",
        mlg: "1180px",
        llg: "1278px",
        xllg: "1300px",
        lllg: "1478px",
      },

      height: {
        fitC: "fit-content",
        "90per": "90%",
      },
      width: {
        "nbx-header-op": "calc(100% - 304px)",
        "nbx-header-cl": "calc(100% - 78px)",
        fit: "fit-content",
      },
      boxShadow: {
        avatar: "0px 0px 0px 2px #FFFFFF, 0px 0px 0px 5px #4DA1FF",
        "avatar-focus": "0px 0px 0px 2px #FFFFFF, 0px 0px 0px 5px #B1DAFF",
        sidebar: "inset -1px 0px 4px rgba(15, 26, 42, 0.1)",
      },
      spacing: {
        "68-17p": "68.17px",
        "14-4p": "14.4px",
        "5-4p": "5.4px",
        "90v": "90vh",
        "95v": "95vh",
      },
      flex: {
        3: "3",
        4: "4",
        6: "6",
      },
      maxWidth: {
        "444p": "444px",
        "736p": "736px",
      },
      minHeight: {
        "236p": "236px",
        "40p": "40px",
      },
      colors: {
        nbxBlue: "#0879FF",
        light: {
          text: {
            base: "#353849",
            muted: "#666D80",
            subtle: "#808897",
            disabled: "#A4ABB8",
            onColorr: "#FFFFFF",
            interactive: "#7F4BF0",
            interactiveHover: "#6025E1",
            success: "#18794E",
            caution: "#866D0B",
            critical: "#B71836",
            info: "#006ADC",
          },
          border: {
            base: "#DFE1E6",
            hover: "#C1C7CF",
            success: "#92CEAC",
            caution: "#EFD36C",
            critical: "#EB9091",
            info: "#96C7F2",
            interactive: "#7F4BF0",
            criticalStrong: "#B71836",
            controlHover: "linear-gradient(180deg, #DFE1E6 0%, #eceff300 100%)",
            borderInput: "#DFE1E6",
            borderInputHover: "#C1C7CF",
            borderInputDisabled: "#ECEFF3",
            baseGradient: "linear-gradient(180deg, #DFE1E6 0%, #dfe1e600 100%)",
          },
          icon: {
            base: "#666D80",
            hover: "#353849",
            disabled: "#A4ABB8",
            onColor: "#FFFFFF",
            interactive: "#7F4BF0",
            interactiveHover: "#6025E1",
            success: "#18794E",
            caution: "#866D0B",
            critical: "#B71836",
            info: "#006ADC",
          },
          background: {
            app: "#FFFFFF",
            appHover: "#ECEFF3",
            surface: "#FFFFFF",
            surfaceHover: "#ECEFF3",
            surfaceHigh: "#FFFFFF",
            surfaceHighHover: "#ECEFF3",
            surfaceLow: "#F6F8FA",
            surfaceLowHover: "#ECEFF3",
            surfaceLowest: "#F6F8FA",
            input: "#FFFFFF",
            inputDisabled: "#F6F8FA",
            success: "#DDF3E4",
            caution: "#FAEDCC",
            critical: "#FFE5E5",
            info: "#E1F0FF",
            interactive: "#6025E1",
            interactiveHover: "#7F4BF0",
            interactiveDisabled: "#F6F8FA",
            chatbarFade:
              "linear-gradient(180deg, #ffffff00 0%, #ffffff99 25%, #FFFFFF 50%, #FFFFFF 75%, #FFFFFF 100%)",
            controlTarget: "#FFFFFF",
            controlTargetActive: "#FFFFFF",
            controlTargetDisabled: "#DFE1E6",
            control: "#DFE1E6",
            controlHover: "#C1C7CF",
            controlDisabled: "#F6F8FA",
          },
          neutral: {
            1000: "#FFFFFF",
            950: "#F6F8FA",
            900: "#ECEFF3",
            800: "#ECEFF3",
            700: "#ECEFF3",
            600: "#FFFFFF",
            500: "rgba(62, 62, 62, 1)",
            400: "#F6F8FA",
            300: "rgba(112, 112, 112, 1)",
            200: "#808897",
            100: "#666D80",
            50: "#353849",
            10: "#353849",
            "00": "#000000",
          },
          accent: {
            600: "rgba(96, 37, 225, 1)",
            400: "rgba(127, 75, 240, 1)",
            300: "rgba(165, 117, 255, 1)",
          },
          red: {
            900: "rgba(41, 20, 21, 1)",
            600: "#EB9091",
            300: "#B71836",
          },
          green: {
            900: "rgba(12, 31, 23, 1)",
            600: "rgba(27, 84, 58, 1)",
            300: "rgba(76, 195, 138, 1)",
          },
          yellow: {
            900: "rgba(34, 26, 0, 1)",
            600: "rgba(89, 74, 5, 1)",
            300: "rgba(240, 192, 0, 1)",
          },
          blue: {
            900: "rgba(15, 27, 45, 1)",
            600: "rgba(10, 68, 129, 1)",
            300: "rgba(82, 169, 255, 1)",
          },
        },
        dark: {
          text: {
            base: "#EDEDED",
            muted: "#A0A0A0",
            subtle: "#7E7E7E",
            disabled: "#606060",
            onColorr: "#FFFFFF",
            interactive: "#A575FF",
            interactiveHover: "#B38AFF",
            success: "#4CC38A",
            caution: "#F0C000",
            critical: "#FF6369",
            info: "#52A9FF",
          },
          border: {
            base: "#2E2E2E",
            hover: "#3E3E3E",
            success: "#1B543A",
            caution: "#594A05",
            critical: "#822025",
            info: "#0A4481",
            interactive: "#7F4BF0",
            criticalStrong: "#B71836",
            controlHover: "linear-gradient(180deg, #2E2E2E 0%, #20202000 100%)",
            controlActive:
              "linear-gradient(180deg, #a575ff4d 0%, #20202000 100%)",
            borderInput: "#3E3E3E",
            borderInputHover: "#606060",
            borderInputDisabled: "#2E2E2E",
            baseGradient: "linear-gradient(180deg, #2E2E2E 0%, #2e2e2e00 100%)",
          },
          icon: {
            base: "#A0A0A0",
            hover: "#EDEDED",
            disabled: "#606060",
            onColor: "#FFFFFF",
            interactive: "#A575FF",
            interactiveHover: "#B38AFF",
            success: "#4CC38A",
            caution: "#F0C000",
            critical: "#FF6369",
            info: "#52A9FF",
          },
          background: {
            app: "#131313",
            appHover: "#202020",
            surface: "#202020",
            surfaceHover: "#282828",
            surfaceHigh: "#1D1D1D",
            surfaceHighHover: "#282828",
            surfaceLow: "#1D1D1D",
            surfaceLowHover: "#2E2E2E",
            surfaceLowest: "#191919",
            input: "#343434",
            inputDisabled: "#282828",
            success: "#0C1F17",
            caution: "#221A00",
            critical: "#291415",
            info: "#0F1B2D",
            interactive: "#6025E1",
            interactiveHover: "#7F4BF0",
            interactiveDisabled: "#282828",
            chatbarFade:
              "linear-gradient(180deg, #13131300 0%, #13131399 25%, #131313 50%, #131313 75%, #131313 100%)",
            controlTarget: "#606060",
            controlTargetActive: "#FFFFFF",
            controlTargetDisabled: "#3E3E3E",
            control: "#343434",
            controlHover: "#3E3E3E",
            controlDisabled: "#282828",
          },
          neutral: {
            1000: "rgba(19, 19, 19, 1)",
            950: "rgba(29, 29, 29, 1)",
            900: "rgba(35, 35, 35, 1)",
            800: "rgba(40, 40, 40, 1)",
            700: "rgba(46, 46, 46, 1)",
            600: "rgba(52, 52, 52, 1)",
            500: "rgba(62, 62, 62, 1)",
            400: "rgba(80, 80, 80, 1)",
            300: "rgba(112, 112, 112, 1)",
            200: "rgba(126, 126, 126, 1)",
            100: "rgba(160, 160, 160, 1)",
            50: "rgba(237, 237, 237, 1)",
            10: "rgba(237, 237, 237, 1)",
            "00": "rgba(255, 255, 255, 1)",
          },
          accent: {
            600: "rgba(96, 37, 225, 1)",
            400: "rgba(127, 75, 240, 1)",
            300: "rgba(165, 117, 255, 1)",
          },
          red: {
            900: "rgba(41, 20, 21, 1)",
            600: "rgba(130, 32, 37, 1)",
            300: "rgba(255, 99, 105, 1)",
          },
          green: {
            900: "rgba(12, 31, 23, 1)",
            600: "rgba(27, 84, 58, 1)",
            300: "rgba(76, 195, 138, 1)",
          },
          yellow: {
            900: "rgba(34, 26, 0, 1)",
            600: "rgba(89, 74, 5, 1)",
            300: "rgba(240, 192, 0, 1)",
          },
          blue: {
            900: "rgba(15, 27, 45, 1)",
            600: "rgba(10, 68, 129, 1)",
            300: "rgba(82, 169, 255, 1)",
          },
        },
      },
      fontFamily: {
        display: [
          "-apple-system",
          "BlinkMacSystemFont",
          "'Segoe UI'",
          "Roboto",
          "Oxygen",
          "Ubuntu",
          "'Fira Sans'",
          "'Droid Sans'",
          "'Helvetica Neue'",
          "sans-serif",
        ],
        body: [
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          '"Liberation Mono"',
          '"Courier New"',
          "monospace",
        ],
        nbxFont: [
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          "Helvetica",
          "Arial",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
        ],
        TWK: [
          "TWKEverett",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          "Helvetica",
          "Arial",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
        ],
      },
      typography: (theme) => ({
        nbx: {
          css: [
            {
              ".title1": {
                fontFamily: "'proxima-nova', sans-serif",
                fontWeight: 500,
                fontSize: "24px",
                lineHeight: "32px",
              },
              ".title2": {
                fontFamily: "'proxima-nova', sans-serif",
                fontWeight: 500,
                fontSize: "20px",
                lineHeight: "normal",
              },
              ".large": {
                fontFamily: "'proxima-nova', sans-serif",
                fontWeight: 400,
                fontSize: "18px",
                lineHeight: "24px",
              },
              ".large-pl": {
                fontFamily: "'proxima-nova', sans-serif",
                fontWeight: 500,
                fontSize: "18px",
                lineHeight: "24px",
              },
              ".regular": {
                fontFamily: "'proxima-nova', sans-serif",
                fontWeight: 400,
                fontSize: "16px",
                lineHeight: "normal",
              },
              ".regular-pl": {
                fontFamily: "'proxima-nova', sans-serif",
                fontWeight: 500,
                fontSize: "16px",
                lineHeight: "normal",
              },
              ".medium": {
                fontFamily: "'proxima-nova', sans-serif",
                fontWeight: 400,
                fontSize: "14px",
                lineHeight: "normal",
              },
              ".medium-pl": {
                fontFamily: "'proxima-nova', sans-serif",
                fontWeight: 500,
                fontSize: "14px",
                lineHeight: "normal",
              },
              ".small": {
                fontFamily: "'proxima-nova', sans-serif",
                fontWeight: 400,
                fontSize: "13px",
                lineHeight: "normal",
              },
              ".small-pl": {
                fontFamily: "'proxima-nova', sans-serif",
                fontWeight: 500,
                fontSize: "13px",
                lineHeight: "normal",
              },
              ".mini": {
                fontFamily: "'proxima-nova', sans-serif",
                fontWeight: 400,
                fontSize: "12px",
                lineHeight: "normal",
              },
              ".mini-pl": {
                fontFamily: "'proxima-nova', sans-serif",
                fontWeight: 500,
                fontSize: "12px",
                lineHeight: "normal",
              },
              ".xmini": {
                fontFamily: "'proxima-nova', sans-serif",
                fontWeight: 400,
                fontSize: "12px",
                lineHeight: "normal",
              },
              ".xmini-pl": {
                fontFamily: "'proxima-nova', sans-serif",
                fontWeight: 500,
                fontSize: "12px",
                lineHeight: "normal",
              },
              ".xxmini": {
                fontFamily: "'proxima-nova', sans-serif",
                fontWeight: 400,
                fontSize: "11px",
                lineHeight: "normal",
              },
            },
          ],
        },
      }),
    },
  },

  plugins: [require("@tailwindcss/typography")],
};
